### ISSUE TITLE
Hangs on "connecting to kernel"

### ISSUE THREAD

**Issue by betatim** [jupytercalpoly/reactive-kernel#15]
This looks super cool, so I wanted to play with it and [launched it on mybinder.org](https://mybinder.org/v2/gh/jupytercalpoly/reactivepy/master). That seems to install the kernel but when I open a new notebook things hang on the "connecting to kernel" stage:

<img width="983" alt="screen shot 2018-08-30 at 20 15 13" src="https://user-images.githubusercontent.com/1448859/44870805-68020b80-ac91-11e8-8f2c-70bdcefe7d18.png">

Any idea what needs to happen to make it run? Maybe there is a missing install step?

**Comment by richagadgil** [comment]
Hi, what version of python are you using?

**Comment by betatim** [comment]
I'm using Python 3. When you launch this repository on mybinder.org it runs `pip install --no-cache-dir .` during the process of creating the docker image.

**Comment by betatim** [comment]
Is there a way to look at the kernel's output/log messages when it starts? Maybe there is something helpful there.

**Comment by willingc** [comment]
I'm getting an error as well but nothing will load for the notebook. We should see what happens if we run it through repo2docker. I'm guessing a dependency is missing or we need a postBuild step related to JS.

**Comment by willingc** [comment]
@betatim Perhaps the best way to make sure that we are all troubleshooting the same config is to create a `binder` directory in this repo. Then, troubleshoot from there.

**Comment by psychemedia** [comment]
Did anyone make any progress getting this to run in MyBinder? I just tried it now and it seems to hangs, as per initial report in this issue.

**Comment by declanvk** [comment]
@psychemedia @betatim Thanks to @gnestor we now have this working in MyBinder if you want to check it out! I would recommend the CitiBikeUsage.ipynb notebook. Here is the [link](https://mybinder.org/v2/gh/jupytercalpoly/reactivepy/master?urlpath=lab/tree/examples/CitiBikeUsage.ipynb).

Closing due #30.

There are definitely going to be other bugs/issues with the kernel, so please file an issue if you find anything!

**Comment by betatim** [comment]
![kapture 2018-12-11 at 23 29 53](https://user-images.githubusercontent.com/1448859/49834485-cb293100-fd9c-11e8-9786-c710d51f440c.gif)

This is very cool!
