### ISSUE TITLE
How this compare to Pluto for julia or observable for js?

### ISSUE THREAD

**Issue by sylvaticus** [jupytercalpoly/reactive-kernel#36]
Is the design similar?

**Comment by declanvk** [comment]
I'm not sure about Pluto, but observable was definitely an inspiration for this project. I think the projects are broadly similar, but have differing levels of integration with the host environment.

Observable has its own parser and runtime:
 - https://github.com/observablehq/parser
 - https://github.com/observablehq/runtime

For reactivepy we reuse some of python's parsing and the runtime is subclassed from IPython's kernel implementation:
 - https://docs.python.org/3/library/symtable.html
 - https://github.com/jupytercalpoly/reactivepy/blob/master/reactivepy/kernel.py

Are there specific elements you're interested in from the design?

**Comment by sylvaticus** [comment]
No,  I was just curious how the different design did compare. Thank you very much for your answer.
